# Generated by Django 4.2.7 on 2024-04-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='flex_time',
            field=models.CharField(blank=True, default='None', max_length=15, null=True),
        ),
    ]
